# Data I Expect to Use for My Project

The data I am expecting to use in my project is an existing dataset from my lab. The dataset contains lab data on soil core samples that were collected from fieldwork in the Hudson Bay lowlands. The dataset contains a variety of biophysical and biochemical metrics for each sample, but I expect to use wavelength reflectance, and carbon and nitrogen content data for my project.

# Legal or Ethical Issues

## Legal Issues
There is a legal issue with the project because the research was supported by grants from the World Wildlife Fund and the Mushkegowuk Council which represents the Cree First Nations of northern Ontario. According to the Tri-Agency Research Data Management Policy, grant recipients should provide appropriate access to the data in accordance with the FAIR (Findable, Accessible, Interoperable, and Reusable) principles and the grant agencies' own guidelines. To address this legal restriction, I will provide figures of my results to the World Wildlife Fund and the Mushkegowuk Council shortly after I have created them, and disclose the raw data to these agencies if requested to do so.

## Ethical Issues
There is an ethical issue with the project because the research was conducted with the Cree First Nations of northern Ontario. According to the Tri-Agency Research Data Management Policy, data management plans must recognize Indigenous data sovereignty and options to renegotiate. To address this ethical restriction, I will co-develop my data management plan with representatives from the Cree First Nations in accordance with the principles and formats they accept.

# Possible Strategies to Build and Protect the Value of the Data

## Where Raw Data Will Be Kept and Backed Up
I will keep and back up my raw data using the 3-2-1 rule. My raw data files will be stored in my lab computer at McMaster University. I will also have an external hard drive to back up my computer. The external hard drive serves as a second copy on a different medium that will back up my raw data files as part of the backup process. Finally, I will also upload my raw data files to Microsoft OneDrive under my McMaster account which will act as an online backup solution.

## File Formats I Anticipate My Data to Be In
I anticipate that my data will only be stored in a CSV file because the equipment used to measure data automatically records it in that file format. The CSV format is an open format which means it is broadly accessible and protected against deprecated systems

## File Naming Convention for My Project Data
The file naming convention for my project data will follow the best practices mentioned in the Reproducible-Research-Workflow repository. I will limit file names to 32 characters maximum and avoid using special characters, periods, hyphens, and spaces. I will use versioning and end my file names using “_v##” where the “##” represents the version number in leading zeros (E.g. “_v03” is version 3). Finally, I will use specific file names to avoid confusion when moved to other folders or computers. In this case, I will use the McMaster project ID number associated with my data so that it is a unique and specific file name while also being identifiable to me and other collaborators involved in the project.  

## Standards That Are Relevant to My Project
The standards relevant to my project are the United States Department of Agriculture Guidelines for Soil Quality Assessment in Conservation Planning and the Government of Canada’s Tri-Agency Research Data Management Policy. Existing standards used in my lab include the Open GeoSpatial Consortium standards and the Institute of Electrical and Electronics Engineers standards and protocols for soil spectroscopy. I might want to create standards that are based on the Tri-Agency Research Data Management Policy in collaboration with representatives from the World Wildlife Fund and the Cree First Nations to help manage my data in accordance with the guidelines of grant agencies involved in my project.

## Possible Strategies Document My Data Throughout My Project
One strategy I might use to document my data throughout my project is to create a repository on GitHub. The repository will contain a README file that introduces and explains what the project is about. Examples of information that will be in the README file include who collected the data and their contact information, what the data is measuring and the purpose of it, methodology for how the data was collected, and other useful information such as the location and date of collection. The README file will also explain how the data is managed, including how it is backed up and the file naming convention. The repository will also contain metadata and data processing files with comments that detail how the data is being processed. This includes code scripts used to process the data, with comments placed above each line of code detailing what they do.
